### ISSUE TITLE
brz 拉力蓝 古铜色轮毂

### ISSUE THREAD

**Issue by rayliu326** [KBRACER/kbracer.github.io#17]
数据 18寸9.5J et 45 轮胎255/35r18
倾角 前后2度
![B2D5B2CC-77CC-4C22-8635-F8EA1B32CC12](https://user-images.githubusercontent.com/109897343/180640346-507af868-a5ca-4cab-8246-b0cad0a3907c.jpeg)
![F035AFA0-E3B9-427D-900C-A0C8B2CCD8FA](https://user-images.githubusercontent.com/109897343/180640347-4599b8f7-5dc7-4165-bd53-8a8bb7f37ccc.jpeg)
![C9842BA8-01E7-4941-9BF9-0B65942B4D31](https://user-images.githubusercontent.com/109897343/180640342-79b1ba65-1752-4c45-aa18-58a52693645d.jpeg)
![60170941-1528-43D9-AF44-EA24F946C99D](https://user-images.githubusercontent.com/109897343/180640344-23944b7b-0379-4b70-853e-4b13af50bd67.jpeg)
![A03AE732-F07D-41E2-B771-2F810D37B855](https://user-images.githubusercontent.com/109897343/180640330-1f191d33-78de-441d-a744-07cc1c46a3fd.jpeg)
![AD4EFD4F-A0B1-43CD-B050-F2FF28DE3B71](https://user-images.githubusercontent.com/109897343/180640333-4b314716-e732-4086-ad5d-0ddf00d9a154.jpeg)
![05782D65-4C2A-4CC3-A8BE-219CA59BAC70](https://user-images.githubusercontent.com/109897343/180640341-b06d772c-4dcb-4849-a248-0eb9b28780e7.jpeg)

**Comment by loveadguard** [comment]
所以，你对教主的网站有什么意见？还是想让他白嫖你的车？如果是这样那么恭喜你痛失一套轮胎，毕竟是轮胎车神教，他能直接把你轮胎磨没
